name: Maven build CI
on: 
  pull_request:
    branches:
      - 3.0.x
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package --file pom.xml
  win-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8 for Windows
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven on Windows
        run: mvn clean package --file pom.xml
